Repository thoth-station/package-analyzer, pull requests merged in 2019-11, with the labels that each got.

#52 Automatic update of dependency thoth-python from 0.6.5 to 0.7.1
  Pipfile.lock
Labels: bot

#53 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#54 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#56 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#55 Propagate document id into job
  openshift/job-template.yaml
Labels: approved, size/XS

#57 Automatic update of dependency thoth-analyzer from 0.1.4 to 0.1.5
  Pipfile.lock
Labels: bot, size/M

#59 Automatic update of dependency thoth-common from 0.9.17 to 0.9.19
  Pipfile.lock
Labels: bot, size/M
