Repository thoth-station/package-analyzer, pull requests merged in 2019-08, with the labels that each got.

#28 Start using Thoth in OpenShift's s2i
  .coafile
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#29 Added config
  .thoth.yaml
Labels: approved, size/S

#32 Remove index key
  thoth/package_analyzer/cli.py
Labels: approved, size/XS
