Repository thoth-station/package-analyzer, pull requests merged in 2019-07, with the labels that each got.

#18 index is really just one index now, not a list of indices
  Pipfile.lock
  thoth/digests_fetcher/cli.py
  thoth/digests_fetcher/python/fetch.py
Labels: approved, size/L

#4 extracting packages & calculating checksums
  .coafile
  README.rst
  app.sh
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
  setup.py
  thoth-digests-fetcher
  thoth-package-analyzer
  thoth/package_analyzer/__init__.py
  thoth/package_analyzer/base.py
  thoth/package_analyzer/cli.py
  thoth/package_analyzer/exceptions.py
  thoth/package_analyzer/python/__init__.py
  thoth/package_analyzer/python/fetch.py
Labels: approved, do-not-merge/work-in-progress, size/L

#22 use generated job id
  openshift/job-template.yaml
Labels: approved, size/XS

#24 return artifacts
  thoth/package_analyzer/python/fetch.py
Labels: approved, size/XS

#25 Add project description and result example
  README.rst
Labels: approved, size/L, size/XXL

#27 Add thoth-infra-stage
  openshift/job-template.yaml
Labels: approved, size/XS

#26 Add files needed to generate documentation
  .coafile
  docs/source/_static/EMPTY
  docs/source/_templates/EMPYT
  docs/source/conf.py
  docs/source/index.rst
Labels: approved, size/L
