Repository thoth-station/package-analyzer, pull requests merged in 2019-09, with the labels that each got.

#30 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#33 Capture Package Not Present on Index
  thoth/package_analyzer/exceptions.py
  thoth/package_analyzer/python/fetch.py
Labels: approved, size/S

#34 Add dry-run
  openshift/job-template.yaml
  thoth/package_analyzer/cli.py
Labels: approved, size/S

#35 Propagate deployment name for sentry environment
  openshift/job-template.yaml
Labels: approved, size/XS

#36 Fix syntax error
  thoth/package_analyzer/cli.py
Labels: approved, size/XS

#37 Automatic update of dependency thoth-python from 0.5.0 to 0.6.3
  Pipfile.lock
Labels: bot

#38 Automatic update of dependency thoth-analyzer from 0.1.2 to 0.1.3
  Pipfile.lock
Labels: bot

#39 Automatic update of dependency thoth-common from 0.9.1 to 0.9.10
  Pipfile.lock
Labels: bot

#40 Calculate package analyzer job duration
  thoth/package_analyzer/cli.py
Labels: approved, size/XS

#41 Automatic update of dependency thoth-analyzer from 0.1.3 to 0.1.4
  Pipfile.lock
Labels: bot
