Repository thoth-station/package-analyzer, pull requests merged in 2019-10, with the labels that each got.

#42 Fix duration
  thoth/package_analyzer/cli.py
Labels: approved, size/XS

#43 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#44 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#45 Automatic update of dependency thoth-python from 0.6.3 to 0.6.4
  Pipfile.lock
Labels: bot

#46 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#49 Automatic update of dependency thoth-python from 0.6.4 to 0.6.5
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#50 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-template.yaml
Labels: approved, size/S
