Repository thoth-station/package-analyzer, pull requests merged in 2020-01, with the labels that each got.

#72 Automatic update of dependency thoth-python from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot, size/L

#73 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#74 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#75 Automatic update of dependency thoth-python from 0.8.0 to 0.9.0
  Pipfile.lock
Labels: bot, size/S

#76 Automatic update of dependency thoth-python from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot, size/XS

#77 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/S

#78 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/M

#79 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/XS

#71 Happy new year!
  docs/source/conf.py
  thoth/package_analyzer/__init__.py
  thoth/package_analyzer/base.py
  thoth/package_analyzer/cli.py
  thoth/package_analyzer/exceptions.py
  thoth/package_analyzer/python/__init__.py
  thoth/package_analyzer/python/fetch.py
Labels: approved, size/S

#80 Automatic update of dependency thoth-analyzer from 0.1.7 to 0.1.8
  Pipfile.lock
Labels: bot, size/M

#81 Automatic update of dependency thoth-common from 0.9.26 to 0.9.27
  Pipfile.lock
Labels: bot, size/XS

#82 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#83 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/XS

#84 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#85 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#87 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/M

#88 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/M
