Repository thoth-station/package-analyzer, pull requests merged in 2020-02, with the labels that each got.

#90 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#91 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#92 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#93 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/S

#94 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#95 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/S

#96 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#97 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/M

#98 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
