Repository thoth-station/package-analyzer, pull requests merged in 2020-04, with the labels that each got.

#108 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#109 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/M

#110 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#111 Fix for template label
  openshift/job-template.yaml
Labels: approved, size/XS

#112 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#113 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/XS

#115 Automatic update of dependency thoth-python from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot, size/S

#116 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/S

#117 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/XS

#118 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/XS

#119 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
